### ISSUE TITLE
Misplaced icons

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#251]
Hi,

I noticed some misplaced icons:

https://abload.de/img/bug2ekrv.png

On the pets card the city icon actually covers the counter for the ressources. Also the card icons themselves seem to be displayed too far down (you can also see this on the Immigrant City in my screenshot).

Or is this already fixed?

**Comment by alrusdi** [comment]
I will check it

**Comment by alrusdi** [comment]
I've fixed resources label overlap by tag igons, but didn't noticed any other icons misplacement. Can it be browser cache problem?

**Comment by dabewi** [comment]
Well, it has something to do with the browser. My standard browser is Chrome and here the symbols are misplaced. But when I open the same page with Firefox, the symbols are correct. Resetting the cache in chrome doesn't work for me. So maybe it's an issue with a specific chrome version.

**Comment by alrusdi** [comment]
I've checked it in Chrome browser too. Also i noticed before that simple Ctrl+R does not clear our cache somehow. Please try to enable developer tools Ctrl+Shift+I and enable "Disable cache" (sic!) checkbox. Let us now if something changed

**Comment by dabewi** [comment]
Hi,

i tested your suggestion, but it didn't solve the problem:

https://abload.de/img/bug6rkbv.png

I run chrome in v. 80.0.3987.100  which should be the actual version.

**Comment by alrusdi** [comment]
I can confirm it. @dabewi thank you for reporting Chrome version. The bug is apearing in new versions of browser. I will try to fix it

**Comment by alrusdi** [comment]
We can fix it by adding empty div before each <div class="content"> block.
Or wrap price and tags elements into div tag (it is better).

But it is kinda monkey work. @bafolts may be it is time to make some kind of "base" template for card and move each unique card html code from HTML_data to corresponding template property of each card component? If my explanations are little obscure I can make prototype of this idea in separate branch to clear what i mean.

**Comment by alrusdi** [comment]
This should be fixed now
